version: 2.1
jobs:
  create_infrastructure:  
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout # check out the code in the project directory
      - run: Ensure backend infrastructure exist
        command: |
          aws cloudformation deploy \
            --template-file template.yml \
            --stack-name my-stack
# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - create_infrastructure